name: flutter_trading_chart
description: Flutter package to display trading charts. It includes tools to draw indicators, customization parameters and panning and zooming abilities on the time axis.
version: 0.0.2
homepage: https://github.com/AmauryBuguet/flutter_trading_chart
repository: https://github.com/AmauryBuguet/flutter_trading_chart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_drawing: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter: